# Generated by Django 4.1 on 2022-09-13 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_panier_client_alter_panier_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='prix',
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=1),
        ),
    ]
